name: Terraform AWS EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to 'main' branch

jobs:
  terraform:
    name: Apply Terraform EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6  # Use the version you're using locally

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change if you're using a different region

    - name: Terraform Init
      run: terraform init

    # - name: Terraform Plan
    #   run: terraform plan

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
    
